# Generated by Django 5.2.6 on 2025-10-01 11:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'device_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.PositiveSmallIntegerField()),
                ('subnet_mask', models.CharField(max_length=255)),
                ('total_addresses', models.BigIntegerField()),
                ('usable_hosts', models.BigIntegerField()),
            ],
            options={
                'db_table': 'subnets',
                'ordering': ['prefix'],
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255, unique=True, validators=[django.core.validators.validate_ipv4_address])),
                ('device_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='ips.branch')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='ips.devicetype')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='ips.subnet')),
            ],
            options={
                'verbose_name': 'IP Address',
                'verbose_name_plural': 'IP Addresses',
                'db_table': 'ips',
                'ordering': ['ip_address'],
            },
        ),
    ]
